FROM python:3.11 AS build

ENV PIP_DISABLE_PIP_VERSION_CHECK=on \
    POETRY_VIRTUALENVS_CREATE=true \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    PIP_NO_CACHE_DIR=off \
    POETRY_VERSION=1.5.1 \
    VIRTUAL_ENV=/src/.venv \
    PATH="/src/.venv/bin:$PATH"

WORKDIR /src

COPY pyproject.toml poetry.lock /src/

RUN pip install "poetry==$POETRY_VERSION"
RUN poetry install --only main

ENTRYPOINT [ "uvicorn",  "src.main:app", "--reload"]