version: "3.9"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devdb
      - POSTGRES_PASSWORD=password
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  # migration:
  #   build:
  #     dockerfile: dockerfile
  #   env_file:
  #     - .env.docker
  #   command: bash -c "aerich upgrade"
  #   volumes:
  #     - .:/usr/src
  #   depends_on:
  #     - db

volumes:
  dbdata:

